spring: #???? ??
  datasource: #???? 2?
    url: jdbc:h2:tcp://localhost/~/reservation #4?
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa: #???? 2?
    hibernate: #???? 4?
      ddl-auto: create #???? 6?
    properties: #???? 4?
      hibernate: #???? 6?
        # show_sql: true #???? 8?
        format_sql: true #???? 8?

logging.level: #???? ??
  org.hibernate.SQL: debug #???? 2?
  org.hibernate.type: trace #???? 2?
